### ISSUE TITLE
OS X Intel/Windows AMD CSG Rendering

### ISSUE THREAD

**Issue by AlexMarinescu** [explosiveduck/ed2d#1]
When trying to render constructive solid geometry on intel graphics card in OS X it will not render anything on screen. "glDrawElements" is suspect as of now, however, it could be a driver bug.

**Comment by mdsitton** [comment]
I also descovered yesterday that this issue also effects the AMD drivers on windows 8.1

**Comment by AlexMarinescu** [comment]
Closed due to it being a python version error.
