### ISSUE TITLE
CSG Sphere does not render

### ISSUE THREAD

**Issue by AlexMarinescu** [explosiveduck/ed2d#2]
Creating a sphere to use with CSG is not rendering properly, subtract causes issues as well.

**Comment by AlexMarinescu** [comment]
Turns out that subtract function in CSG does not work between the two cubes, it could be a depth issue, or it could be a rendering issue like the sphere due to how the triangles get arranged.

**Comment by AlexMarinescu** [comment]
Looks like the indexer count and vertices count for the sphere object are not correct which most likely will cause the rest of the issues.

**Comment by mdsitton** [comment]
This is also probably related to issue #1 :P
(Just thowing this here so the issue shows up in the other issue btw)

**Comment by AlexMarinescu** [comment]
So after further investigation, both cylinder and sphere csg functions have the same issues. In other words, vertices count is not actual therefore it will not upload correctly to the GPU. The cube function seems to work as expected but regardless I'm not sure what the cause is yet.

**Comment by AlexMarinescu** [comment]
Turns out the code is fine except when you run it with python 2.x the cylinder and sphere code do not work due to some changes that were made in python 3. So I will close this issue for now.
