### ISSUE TITLE
Take a look at a secondary restructure of the framework code.

### ISSUE THREAD

**Issue by mdsitton** [explosiveduck/ed2d#6]
Currently the framework code is isolated from the game data files somewhat, and a sort of hack workaround fixes this to a degree. What should happen is all of the data files should be in the same location as the game that ends up being ran.

So i think this rework should basically move the data files into the framework folder, then move the engine using game source code into a sub directory of this folder could be called game or something. This would basically move the framework folder into a role of being a project structure for users to start their games from.

Thoughts?

**Comment by AlexMarinescu** [comment]
Well first off all we should probably try and avoid using hack fixes at this stage unless there is no other way to do it. 

Secondly, correct me if I'm wrong but what you wanna do is move "Data" inside "Framework" and then create a folder called "Game" and dump all game related code in there? If that what you wanna do then I agree that makes sense to me, would be a lot better from what it is now.

**Comment by mdsitton** [comment]
Alright then ill do it real quick.

**Comment by mdsitton** [comment]
Ok this is implemented now.
